Repository nimblehq/react-templates, pull requests merged in 2022-06, with the labels that each got.

#84 [#83] Fix: Move the publish workflow to the right folder
  .github/workflows/publish.yml
Labels: type : bug

#91 Update CODEOWNERS
  .github/CODEOWNERS
Labels: type : chore

#90 [#86] Update Wiki to add the list of Existing Features
  .github/wiki/Home.md
  .github/workflows/wiki.yml
  README.md
Labels: type : chore

#92 [#87] Add recommended libraries from the Varuna Web project
  .github/wiki/Home.md
Labels: @2.3.0
