Repository nimblehq/react-templates, pull requests merged in 2022-07, with the labels that each got.

#98 Release 2.3.0
  .github/CODEOWNERS
  .github/wiki/Home.md
  .github/workflows/publish.yml
  .github/workflows/wiki.yml
  README.md
  package.json
  template/.github/workflows/preview.yml
Labels: type : release

#107 [#96] Add tailwind add-on
  packages/cli-tool/src/add-ons/ui-framework/bootstrap.ts
  packages/cli-tool/src/add-ons/ui-framework/index.ts
  packages/cli-tool/src/add-ons/ui-framework/tailwind-css.ts
  packages/cli-tool/src/add-ons/version-control/index.ts
  packages/cli-tool/src/commands/generate/index.ts
  packages/cli-tool/src/helpers/child-process.ts
  packages/cli-tool/src/helpers/choices.ts
  packages/cli-tool/src/helpers/file-editor.ts
  packages/cli-tool/src/helpers/file.ts
  packages/cli-tool/src/template/initialize-cra-app.ts
  packages/cra-template/template/.add-ons/tailwind/postcss.config.js
  packages/cra-template/template/.add-ons/tailwind/stylesheets/application.css
  packages/cra-template/template/.add-ons/tailwind/stylesheets/dummy.css
  packages/cra-template/template/.add-ons/tailwind/tailwind.config.js
Labels: type : feature, @2.4.0

#110 [#109] Update PR templates
  .github/PULL_REQUEST_TEMPLATE.md
  packages/cra-template/template/.github/PULL_REQUEST_TEMPLATE.md
  packages/cra-template/template/.gitlab/merge_request_templates/Default.md
Labels: type : chore, @2.4.0

#114 [#106] Add publish workflow using Lerna
  .github/workflows/publish.yml
  package-lock.json
  packages/cli-tool/.gitignore
  packages/cli-tool/package.json
  packages/cli-tool/src/add-ons/ui-framework/bootstrap.ts
  packages/cli-tool/src/add-ons/ui-framework/index.ts
  packages/cli-tool/src/add-ons/ui-framework/tailwind-css.ts
  packages/cli-tool/src/add-ons/version-control/index.ts
  packages/cra-template/package.json
Labels: type : chore

#112 [#104] Add tests for add-ons
  .github/workflows/test-cli-tool.yml
  .github/workflows/test-cra-template.yml
  .gitignore
  package-lock.json
  packages/cli-tool/.mocharc.json
  packages/cli-tool/README.md
  packages/cli-tool/package.json
  packages/cli-tool/src/add-ons/ui-framework/bootstrap.ts
  packages/cli-tool/src/add-ons/ui-framework/index.ts
  packages/cli-tool/src/add-ons/ui-framework/tailwind-css.ts
  packages/cli-tool/src/add-ons/version-control/index.ts
  packages/cli-tool/src/commands/generate/index.ts
  packages/cli-tool/src/helpers/child-process.ts
  packages/cli-tool/src/template/initialize-cra-app.ts
  packages/cli-tool/test/add-ons/ui-framework/bootstrap.ts
  packages/cli-tool/test/add-ons/ui-framework/tailwind-css.ts
  packages/cli-tool/test/add-ons/version-control/index.ts
  packages/cli-tool/test/commands/generate/index.test.ts
  packages/cli-tool/test/helpers/init.js
  packages/cli-tool/test/helpers/init.ts
  packages/cli-tool/test/helpers/test-data.ts
  packages/cli-tool/test/helpers/test-scenario.ts
  packages/cli-tool/test/hooks/initialize/generate-base-app.test.ts
  packages/cli-tool/test/tsconfig.json
Labels: type : chore
