Repository nimblehq/react-templates, pull requests merged in 2022-04, with the labels that each got.

#56 [#28] Add the Github Actions test workflow template for React projects
  template.json
  template/.github/workflows/test.yml
Labels: type : feature

#60 [#52] Replace `node-sass` with Dart SASS
  template.json
Labels: type : chore, @2.2.0

#61 [#53] Add react-router to the template
  template.json
  template/src/App.tsx
  template/src/index.tsx
  template/src/routes/index.tsx
  template/src/screens/.keep
  template/src/screens/Home.test.tsx
  template/src/screens/Home.tsx
  template/tsconfig.json
Labels: type : feature, @2.2.0

#71 [#63] Add .tool-versions file in the template folder
  template/.tool-versions
Labels: type : bug

#68 [#67] Update the project's maintainers info
  .github/CODEOWNERS
Labels: type : chore, @2.2.0

#62 [#51] Add the Github Actions build/deploy workflows
  template/.github/workflows/deploy.yml
  template/.github/workflows/deploy_preview.yml
  template/README.md
Labels: @2.2.0

#73 [#66] Support only one package manager or keep both? (use only npm)
  README.md
  template.json
  template/.github/workflows/deploy.yml
  template/.github/workflows/deploy_preview.yml
  template/README.md
  template/gitignore
  template/public/index.html
Labels: @2.2.0

#70 [#69] Add a GitHub Action for displaying Jest test coverage information in pull requests
  template.json
  template/.github/workflows/test.yml
  template/dangerfile.ts
Labels: @2.2.0

#75 [#65] Update template to use the new API in React 18
  template.json
  template/src/index.tsx
Labels: type : chore

#76 [#74] Update ESLint/stylelint configurations to use Nimble shared configurations
  .github/workflows/test.yml
  template.json
  template/.eslintrc.js
  template/.github/workflows/test.yml
  template/src/types/react-i18next.d.ts
  template/stylelint.config.js
Labels: type : chore
