Repository nimblehq/react-templates, pull requests merged in 2022-03, with the labels that each got.

#37 [#34] Add localization feature to manage translations and reuse labels
  template.json
  template/README.md
  template/env.example
  template/public/locales/en/translation.json
  template/src/App.test.tsx
  template/src/App.tsx
  template/src/__mocks__/i18n.ts
  template/src/__mocks__/react-i18next.ts
  template/src/i18n.ts
  template/src/index.tsx
  template/src/types/react-i18next.d.ts
Labels: type : feature

#42 [#30] Add testIdAttribute configuration for @testing-library/react
  template/src/App.test.tsx
  template/src/App.tsx
  template/src/lib/requestManager.test.ts
  template/src/lib/requestManager.ts
  template/src/setupTests.ts
Labels: type : feature

#41 [#31] Fix: Cypress testing library command not found
  template.json
  template/cypress/integration/init.spec.ts
  template/cypress/support/commands.ts
Labels: type : bug, @2.1.0

#45 [#44] Fix: cannot find module 'tests/error' linting error
  template/src/lib/requestManager.test.ts
Labels: type : bug, @2.1.0

#47 [#46] Add Engine version and .tools-version file to make it clearer about using Node 14
  .nvmrc
  .tool-versions
  README.md
  package.json
  template.json
  template/src/reportWebVitals.ts
Labels: type : chore, @2.1.0

#48 [#43] Update Prettier and ESLint rules to make it consistent with our convention
  template.json
  template/.eslintrc.js
  template/.prettierrc
  template/cypress/integration/init.spec.ts
  template/cypress/plugins/index.ts
  template/cypress/support/component-selector.ts
  template/cypress/support/configure-testing-library.ts
  template/gitignore
  template/src/App.test.tsx
  template/src/App.tsx
  template/src/__mocks__/i18n.ts
  template/src/__mocks__/react-i18next.ts
  template/src/i18n.ts
  template/src/index.tsx
  template/src/lib/requestManager.test.ts
  template/src/lib/requestManager.ts
  template/src/reportWebVitals.ts
  template/src/setupTests.ts
  template/src/types/react-i18next.d.ts
Labels: type : chore, @2.1.0
