Repository nimblehq/react-templates, pull requests merged in 2022-05, with the labels that each got.

#77 Release 2.2.0
  .github/CODEOWNERS
  .github/workflows/test.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  template.json
  template/.eslintrc.js
  template/.github/workflows/deploy.yml
  template/.github/workflows/deploy_preview.yml
  template/.github/workflows/test.yml
  template/.gitlab/merge_request_templates/Default.md
  template/.gitlab/merge_request_templates/Release.md
  template/.tool-versions
  template/README.md
  template/dangerfile.ts
  template/gitignore
  template/public/index.html
  template/src/App.tsx
  template/src/index.tsx
  template/src/routes/index.tsx
  template/src/screens/.keep
  template/src/screens/Home.test.tsx
  template/src/screens/Home.tsx
  template/src/types/react-i18next.d.ts
  template/stylelint.config.js
  template/tsconfig.json
Labels: type : release

#78 [#54] Migrate from @import to @use and @forward
  template/.npmrc
  template/src/assets/stylesheets/_variables.scss
  template/src/assets/stylesheets/application.scss
  template/src/dummy.scss
Labels: type : chore

#80 Release 2.2.1
  package.json
  template/.npmrc
  template/src/assets/stylesheets/_variables.scss
  template/src/assets/stylesheets/application.scss
  template/src/dummy.scss
Labels: type : release

#81 [#58] Add a Github workflow to publish the package to the NPM registry
  template/.github/workflows/publish.yml
Labels: type : feature
